---
title: "Final Project"
author: "Volodymyr Kotov"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

devtools::install_github("GIScience/openrouteservice-r")
```

```{r include=FALSE}

packages<-c(
  "maptools",
  "rgdal",
  "maps",
  "jsonlite",
  "RColorBrewer",
  "ggmap",
  "shiny",
  "leaflet",
  "flexdashboard",
  "rnaturalearth",
  "wbstats",
  "DT",
  "ggplot2",
  "magrittr",
  "rvest",
  "readxl",
  "tidyverse",
  "dplyr",
  "scales",
  "readxl",
  "rstatix",
  "janitor",
  "flextable",
  "ggcorrplot",
  "glmnet"
)

library(readr)
library(sf)
library(leaflet.extras)
library(dbscan)
library(openrouteservice)
library(geosphere)
library(magrittr)
library(mapview)
library(tidygeocoder)
library(osmdata)

#if(!require("pacman")) install.packages("pacman")

#pacman::p_load(packages, character.only = T)
sapply(packages, require, character.only = TRUE)

```


``` {r include=FALSE}

setwd("~/Desktop/KSE/Data Analysis in R/Project_1")

df <- read_csv("melb_data.csv")
df1 <- df %>% 
  select(.,c("Suburb","Address","Rooms","Price","Distance","BuildingArea","Lattitude","Lattitude","Regionname"))

```


```{r include=FALSE}

df1_summ <- df1 %>% 
  select(., c("Rooms","Price","Distance","BuildingArea","Regionname"))

```


Column {data-width=450}
-----------------------------------------------------------------------

### 3.Descriptive statistics

```{r echo=FALSE}

server <- function(input, output, session) {
  
  #by district 
  table <- df1 %>% 
    group_by(Regionname) %>%                      
    summarise(                                           
      N = n(),                                            
      mean_price = mean(Price, na.rm=T),
      min_price = min(Price),
      max_price = max(Price),
      std = sqrt(var(Price)))  
  
  output$table = renderTable(table)
}

#inssert the number of rows
ui <- basicPage(
   fluidRow(
        column(6,
          tableOutput('table'))
  )
)

shinyApp(ui, server)

```

### 4.Histograms

```{r echo=FALSE}

options(scipen=999)

server <- function(input, output, session) {
  
#insert appropriate name
 data1 <- reactive({
    req(input$region)
    df2 <- df1 %>% filter(Regionname %in% input$region)
  })
  
  output$plot <- renderPlot({
    
     ggplot(data1(), aes(x=Price)) +
  geom_histogram(aes(y = ..density..), color = "#000000", fill = "#69b3a2") +
  geom_density(color = "#000000", fill = "#F85700", alpha = 0.6) +   
  labs(title="Price Distribution Rough", 
       caption="Graph: Histogram",x = "Price", y = "Density")
  })
}
ui <- basicPage(
  selectInput("region","Choose a region:", c(unique(df1$Regionname))),
  plotOutput("plot")
)

shinyApp(ui, server)

```

Column {data-width=500}
-----------------------------------------------------------------------

### 5.Correlation matrix

```{r echo=FALSE}

df3 <- na.omit(df1[,c("Rooms","Price","Distance","BuildingArea")])
corr <- round(cor(df3), 1)

ggcorrplot(
  corr,
  hc.order = TRUE,
  type = "lower",
  outline.color = "white",
  ggtheme = ggplot2::theme_gray,
  colors = c("#6D9EC1", "white", "#E46726")
)

```

### 6.Map

```{r echo=FALSE}

#in this section i found some useful code

#this is how you can change your address to long and lat
#lat_longs <- addr %>%
#  geocode(Address, method = 'osm', lat = latitude , long = #longitude)

#example how you can mutate your geocode to appropriate file
#addr.geo <- mutate_geocode(addr, location = Address, output = "latlona")

#you need to form a dataframe then
#addr <- data.frame(Address = c("Київ, Мала Житомирська 13/6"),
#                   College = c("Colby"),
#                   stringsAsFactors = FALSE)

```

```{r echo = FALSE}

#layout

basemap <- leaflet() %>%
  # add different provider tiles
  addProviderTiles(
    "OpenStreetMap",
    # give the layer a name
    group = "OpenStreetMap"
  ) %>%
  addProviderTiles(
    "Stamen.Toner",
    group = "Stamen.Toner"
  ) %>%
  addProviderTiles(
    "Stamen.Terrain",
    group = "Stamen.Terrain"
  ) %>%
  addProviderTiles(
    "Esri.WorldStreetMap",
    group = "Esri.WorldStreetMap"
  ) %>%
  addProviderTiles(
    "Wikimedia",
    group = "Wikimedia"
  ) %>%
  addProviderTiles(
    "CartoDB.Positron",
    group = "CartoDB.Positron"
  ) %>%
  addProviderTiles(
    "Esri.WorldImagery",
    group = "Esri.WorldImagery"
  ) %>%
# add a layers control
  addLayersControl(
    baseGroups = c(
      "OpenStreetMap", "Stamen.Toner",
      "Stamen.Terrain", "Esri.WorldStreetMap",
      "Wikimedia", "CartoDB.Positron", "Esri.WorldImagery"
    ),
    # position it on the topleft
    position = "topleft"
  )


```

```{r echo = FALSE}

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=30.542721, lat=50.447731, popup="The birthplace of R")

#this is if you want not only a dot on the map, but an icon
#i find it useless
icon.fa <- makeAwesomeIcon(
  icon = "flag", markerColor = "red",
  library = "fa",
  iconColor = "black"
)

#in this section you add properties of your markers
map_1 <- basemap %>%
  addProviderTiles("CartoDB.DarkMatter") %>% 
  addCircleMarkers(
   lat = 50.447731,
   lng = 30.542721,
   color = "#E2E2E2",
    # set the opacity of the circles
    opacity = 0.65,
    # set the radius of the circles
    radius = 4,
    # create custom labels
    label = paste(
      "Name:", "X","<br>",
      "Cluster:","X" ,"<br>",
      "Cluster size:", "x","<br>",
      "Street: ", "X"
    ) %>%
      lapply(htmltools::HTML)
)

map_1

```
### 7. Association 

```{r echo = FALSE}

#the key idea was to find in text TOP 10 words that show the importance of certain factors

```

### 8. Barplots on the number of rooms in Kyiv

```{r echo = FALSE}

#the key idea was to allow the user to select the district and then to check the mean price of the barplot in case of different number of room

```

### 9. Top 10 expensive streets in Kyiv

```{r echo = FALSE}

#the key idea was to group_by() streets in Kiev and summarize() the mean price
#then make a ggplot() with bars

```

### 10. Prediction

```{r echo = FALSE}

#create a separate df for the further work

ui <- basicPage(
  sidebarLayout(
    sidebarPanel(
      helpText("Create demographic maps with 
               information from the 2010 US Census."),
      sliderInput("room", 
                  label = "Select the number of rooms you want: ",
                  min = 1, max = 5, value = 1),
      sliderInput("sqr_m", 
                  label = "Select a desired size: ",
                  min = 1, max = 140, value = 1),
      #will be needed once you have the floor number
      #sliderInput("floor", 
      #            label = "Select the floor you want: ",
      #            min = 1, max = 20, value = 1),
      sliderInput("time", 
                  label = "Select time spent to the nearest metro station: ",
                  min = 1, max = 20, value = 0.5)
    ),
      textOutput("text")
  )
)

server <- function(input, output, session) {
  
#insert appropriate name
 data2 <- reactive({
    req(input$time)
    #req(input$floor)
    req(input$room)
    req(input$sqr_m)
    df2 <- c(input$room,input$time,input$sqr_m) # also add input$floor
  })
 
 #clean your data
 df6 <- na.omit(df1)
 #select the prediction variable
 y <- df6$Price
 #select predictors by removing all the not needed params
 x <- df6 %>% 
  select(., !c("Price","Lattitude","Address","Suburb","Regionname"))
 #make them as matrix
 x <- as.matrix(x)
 #apply cross validation
 cv_model <- cv.glmnet(x, y, alpha = 1)
 #select the best parameter and make a prediction based on it
 best_lambda <- cv_model$lambda.min
 best_model <- glmnet(x, y, alpha = 1, lambda = best_lambda)

  output$text <- renderText({
    new = matrix(data2(), nrow=1, ncol=3) 
    paste("The approximate value is: $",round(predict(best_model, s = best_lambda, newx = new),2))
  })
}

shinyApp(ui, server)

```

