---
runtime: shiny
title: "WDI Dashboard"
author: "by √3kT/m"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(htmltools)
library(shiny)
library(shinydashboard)
library(shinycssloaders)
library(shinyWidgets)
library(leaflet)
library(WDI)
library(bslib)
library(plotly)
library(ggplot2)
library(data.table)
library(leaflet)
library(geojsonio)
library(rstudioapi)
```

```{r import-data}

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

source("apps/data/get-data.r", chdir=T)
source("apps/choose-country-list/choose-country-list.R", chdir=T)
source("apps/choose-country-map/choose-country-map.R", chdir=T)
source("apps/choose-indicator/choose-indicator.R", chdir=T)
source("apps/choose-date/choose-date.R", chdir=T)

```

```{r ploting}
  #function for linear plotting  
    line_plot <- function(selectData, indicator){
        plot <- ggplot() +
          geom_line(selectData, mapping = aes(year, value, colour = country), size=2) +
          ylab("value") +
          scale_fill_brewer(palette = "RdPu")+
          scale_y_log10()+
          labs(
            x = "Year",
            y= indicator
          )+
        theme(
        panel.background = element_blank(),
        plot.background = element_blank(),
        panel.grid = element_line(colour = "grey"),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(face = "bold", size = 15),
        axis.title.y = element_text(face = "bold", size = 15),
        axis.text.x = element_text(face = "bold", size = 15),
        axis.text.y = element_text(face = "bold", size = 15)
        )
        return(plot)}
  #function for area plotting  
    area_plot <- function(selectData, indicator){
        plot <- ggplot() +
          geom_area(selectData, mapping = aes(year, value, fill = country)) +
          ylab("value") +
          scale_fill_brewer(palette = "YIGn")+
          labs(
            x = "Year",
            y= indicator
          )+
        theme(
        panel.background = element_blank(),
        plot.background = element_blank(),
        panel.grid = element_line(colour = "grey"),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(face = "bold", size = 15),
        axis.title.y = element_text(face = "bold", size = 15),
        axis.text.x = element_text(face = "bold", size = 15),
        axis.text.y = element_text(face = "bold", size = 15)
        )
        return(plot)}

```

Indicators Overview 
===================================== 
```{r Education Indicators Overview }

shinyApp(
  ####
  #UI#
  ####
  ui=fluidPage(theme = bs_theme(version = 4, bootswatch = "minty"),
               tags$head(tags$style(
      HTML(
        "
    .leaflet-container {
    background-color:rgba(255,0,0,0.0);}
    
    #myMap {height: calc(100vh) !important;}
    "
        )
    )),
    sidebarLayout(
      sidebarPanel(
        fluidRow(
          sliderInput("rangevalues",
  label = strong("Select Total Expenditure on Education (% of government spending)"),
  min = min.expenditure, max = max.expenditure,
  value = c(min.expenditure, max.expenditure/2), 
  step = 0.1,
  sep="",
  width = "100%"
  )
  ),
    fluidRow(
      helpText(
        "Select expenditure range to display on the map"
      )),  
  hr(),
  fluidRow(
          ChooseCountryListUI("Vova_Country",WB_CountryPolygons[WB_CountryPolygons$ISO_A3_EH %in% countries.of.interest,]$NAME_EN)
        ),
  strong(textOutput("titlebar")),
      fluidRow(
        column(width = 12,
         withSpinner( plotOutput("barplot"), color = "#80c4ac")
        )
      ),
  strong(textOutput("titlescatter")),
  fluidRow(
        column(width = 12,
         withSpinner( plotOutput("scatterplot"), color = "#80c4ac")
        )
      )
    ),
      mainPanel(
    fluidRow(column(width = 12,
      withSpinner(leafletOutput(
        outputId = "myMap", width = "100%"
      ), color = "#80c4ac")
    ))
      )
    )
  ),
  ########
  #SERVER#
  ########
  server = function(input, output) {
    
    country <- ChooseCountryListServer("Vova_Country")
    groups <- reactiveValues(count = 0)
    
    foundational.map <- reactive({
      leaflet() %>%
        addPolygons(
          data = polygons.of.interest,
          layerId = polygons.of.interest$NAME_EN,
          group = "base",
          fill = TRUE,
          fillColor = palette(polygons.of.interest$EDUC), 
          fillOpacity = 1,
          weight = 1,
          color = "#80c4ac",
          label = paste0(
            "<strong>Country: </strong>",
            polygons.of.interest$NAME_EN,
            "<br/> ",
            "<strong>Year: </strong>",
            polygons.of.interest$EDUC.YEAR,
            "<br/>",
            "<strong>Total exp.(%): </strong>",
            round(polygons.of.interest$EDUC, 2),
            "<br/> "
          ) %>% lapply(htmltools::HTML),
          labelOptions = labelOptions(noHide = FALSE)
        ) %>% setView(lng = 16.1657
                      ,
                      lat = 50.4515
                      ,
                      zoom = 4) %>%
        setMaxBounds(
          lng1 = 16.1657
          ,
          lat1 = 50.4515
          ,
          lng2 = 16.1657
          ,
          lat2 = 50.4515
        )%>%
   addLegend(position = "bottomright",
      colors= palette(unique(data.frame(NAME_EN=polygons.of.interest$NAME_EN, EDUC = polygons.of.interest$EDUC))$EDUC), labels = paste0(
       unique(data.frame(NAME_EN=polygons.of.interest$NAME_EN, EDUC = polygons.of.interest$EDUC))$NAME_EN,
            " - ",
            round(unique(data.frame(NAME_EN=polygons.of.interest$NAME_EN, EDUC = polygons.of.interest$EDUC))$EDUC, 2), " %"
          ),
      opacity = 1, title = "Total exp.(%)"
    )
    })
    
    observeEvent(input$rangevalues, {
      groups$count = groups$count + 1
      
      lines.of.interest <-
        polygons.of.interest[which(
          !is.na(polygons.of.interest$EDUC) &
            polygons.of.interest$EDUC <= input$rangevalues[1] |
            polygons.of.interest$EDUC >= input$rangevalues[2]
        ), ]
      
      leafletProxy(mapId = "myMap") %>%
        addPolygons(
          data = lines.of.interest,
          layerId = lines.of.interest@data$id,
          group = as.character(groups$count),
          fill = TRUE,
          fillColor = "#f8f4f4",
          fillOpacity = 1,
          weight = 1,
          color = "#5a5a5a",
          highlightOptions = highlightOptions(
            weight = 4,
            color = "#80c4ac",
            bringToFront = F
          ),
          label = paste0(
            "Country: ",
            lines.of.interest$NAME_EN,
            "<br/> ",
            "Year: ",
            lines.of.interest$EDUC.YEAR,
            "<br/>",
            "Total exp.(%): ",
            round(lines.of.interest$EDUC, 2),
            "<br/> "
          ) %>% lapply(htmltools::HTML),
          labelOptions = labelOptions(noHide = FALSE)
        ) %>% clearGroup(as.character(groups$count - 1))
    }, ignoreNULL = FALSE)
    
    observeEvent(country,{
    output$barplot <- renderPlot({
      ggplot(country.data[country.data$iso3c == country(),])+
        geom_bar(stat="identity", mapping = aes(x = indicator, y = value, fill=indicator))+
        geom_label(mapping = aes(label = paste0(round(value,2)," %"), y =value, x = indicator), fill = "#f8949c")+
        theme(
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        panel.background = element_blank(),
        plot.background = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(face = "bold", size = 15),
        legend.position = "none"
        )+
        labs(
          x="",
          y="",
          title =""
        )+
      coord_flip()+
        scale_fill_brewer(palette = "Greens")
      
    }, bg="transparent")
    
    output$scatterplot <- renderPlot({
      ggplot(gdp.data[gdp.data$iso3c == country(),])+
        geom_point(mapping = aes(x = SE.XPD.TOTL.GB.ZS, y = NY.GDP.MKTP.KD/(10^9)), color = "#f8949c", size = 4)+ 
        geom_smooth(mapping = aes(x = SE.XPD.TOTL.GB.ZS, y = NY.GDP.MKTP.KD/(10^9)), method=lm , color= "#80c4ac", se=TRUE) +
        theme(
        panel.background = element_blank(),
        plot.background = element_blank(),
        panel.grid = element_line(colour = "grey"),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(face = "bold", size = 15),
        axis.title.y = element_text(face = "bold", size = 15),
        axis.text.x = element_text(face = "bold", size = 15),
        axis.text.y = element_text(face = "bold", size = 15)
        )+
        labs(
          x="Total Expenditure on Education (% of government spending)",
          y="GDP (bln. const. USD 2015)",
          title = 
        )
    }, bg="transparent")
    
    output$titlebar <- renderText({paste0("Educational Attainment in ",WDI_Countries[WDI_Countries$Country.iso3c == country(),1])})
    output$titlescatter <- renderText({paste0("Education Expenditures vs. GDP in ", WDI_Countries[WDI_Countries$Country.iso3c == country(),1])})
    
    }, ignoreNULL = FALSE)
    
    
    output$myMap <- renderLeaflet({
      foundational.map()
    })
    
  }
)

```

Countries Overview 
=====================================  

```{r, warning=FALSE}
shinyApp(
  ####
  #UI#
  ####
  ui = fluidPage(
    theme = bs_theme(version = 4, bootswatch = "minty"),
    sidebarLayout(
      sidebarPanel(
        actionButton("update","Update View", icon("refresh"), width = "100%"),
        hr(),
        ChooseCountryMapUI("1"),
        ChooseIndicatorListUI("2"),
        ChooseDateUI("3")
        
      ),
      mainPanel(tabsetPanel(
        type = "tabs",
        tabPanel("Custom",
                 div(
                   br(),
                   selectizeInput(
                     inputId = 'selectIndicator',
                     label = strong('Custom Plot Selector'),
                     choices = c("GDP per capita (constant 2015 US$)"),
                     selected = c("GDP per capita (constant 2015 US$)"),
                     multiple = FALSE,
                     options = list(create = FALSE),
                     width = "100%",
                   ),
                   radioGroupButtons(
                     inputId = "change_plot",
                     choices = c(
                       `<i class='fa fa-line-chart'></i>` = "line",
                       `<i class='fa fa-area-chart''></i>` = "area"),
                     justified = TRUE,
                     selected = "line")),
                   helpText(
                     "Select indicator and type of plot would you like to construct. You can also find some data if you select an area on the plot in a 'rectangle'"),
                   hr(),
                 withSpinner(
                 plotOutput("firstPlot",
                            width = "100%",
                            height = "300px",
                            brush = "plot_brush"),
                 color = "#80c4ac"),
                 tableOutput("data")
                 ),
                
        tabPanel(
          "Overview",
          br(),
          fluidRow(
            column(width = 12,
            withSpinner(plotlyOutput(outputId = "plot1", width = "100%"),color = "#80c4ac")
            )
          ),
          fluidRow(
            column(width = 12,
            withSpinner(plotlyOutput(outputId = "plot2", width = "100%"),color = "#80c4ac")
            )
          ),
          fluidRow(
            column(width = 12,
            withSpinner(plotlyOutput(outputId = "plot3", width = "100%"),color = "#80c4ac")
            )
          ),
          fluidRow(
            column(width = 12,
            withSpinner(plotlyOutput(outputId = "plot4", width = "100%"),color = "#80c4ac")
            )
          ),
          fluidRow(
            column(width = 12,
            withSpinner(plotlyOutput(outputId = "plot5", width = "100%"),color = "#80c4ac")
            )
          ),
          fluidRow(
            column(width = 12,
            withSpinner(plotlyOutput(outputId = "plot6", width = "100%"),color = "#80c4ac")
            )
          )
          )
          
        
             
          )
        )
      )
      
    ),
  ########
  #SERVER#
  ########
  server = function(input, output) {
    
    country.list <- ChooseCountryMapServer("1")
    indicator.list <- ChooseIndicatorListServer("2")
    date.list <- ChooseDateServer("3")
    
    observeEvent(input$update,{
      updateSelectizeInput(session = getDefaultReactiveDomain(),'selectIndicator', choices = WDI_Indicators[WDI_Indicators$Indicator.Code %in% indicator.list(), 1]  )
    },ignoreNULL = FALSE)
    
    selectData <- eventReactive(input$update,{
      
      req(country.list(),indicator.list(),date.list(),cancelOutput = TRUE)
        
      return(melt(setDT(WDI(
        country = country.list(),
        indicator = indicator.list(),
        start = date.list()[1],
        end = date.list()[2]
      )),id.vars = c("country","iso2c","iso3c","year"),
                     variable.name = "indicator"))
      
      },ignoreNULL = FALSE)

    
###Page1###
    
    output$firstPlot <- renderPlot({
      
      if (input$change_plot %in% "line") {
        line_plot(selectData()[selectData()$indicator == WDI_Indicators[WDI_Indicators$Indicator.Name == input$selectIndicator, 2],],input$selectIndicator)
      } else {
        area_plot(selectData()[selectData()$indicator == WDI_Indicators[WDI_Indicators$Indicator.Name == input$selectIndicator, 2],],input$selectIndicator)
      }
    })
    
###SecondPage###
    #1#
    
    n <- reactive({length(unique(selectData()$indicator))})
    
    #2# 
    plot1 <-eventReactive(input$update,{
      if (n()>=1){line_plot(selectData()[selectData()$indicator == unique(selectData()$indicator)[1],],WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[1],1])+
          theme(
            axis.title.y = element_blank()
          )+
          labs(
            title = WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[1],1]
          )
          }
      else
      {return(NULL)}
     },ignoreNULL = FALSE)
    
    #2# 
    plot2 <- eventReactive(input$update,{
      if (n()>=2){line_plot(selectData()[selectData()$indicator == unique(selectData()$indicator)[2],],WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[2],1])+
          theme(
            axis.title.y = element_blank()
          )+
          labs(
            title = WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[2],1]
          )}
      else
      {return(NULL)}
     },ignoreNULL = FALSE)
    
    #3# 
    plot3 <- eventReactive(input$update,{
      if (n()>=3){line_plot(selectData()[selectData()$indicator == unique(selectData()$indicator)[3],],WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[3],1])+
          theme(
            axis.title.y = element_blank()
          )+
          labs(
            title = WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[3],1]
          )}
      else
      {return(NULL)}
     },ignoreNULL = FALSE)
    
    #4# 
    plot4 <- eventReactive(input$update,{
      if (n()>=4){line_plot(selectData()[selectData()$indicator == unique(selectData()$indicator)[4],],WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[4],1])+
          theme(
            axis.title.y = element_blank()
          )+
          labs(
            title = WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[4],1]
          )}
      else
      {return(NULL)}
     },ignoreNULL = FALSE)
    
    #5# 
    plot5 <- eventReactive(input$update,{
      if (n()>=5){line_plot(selectData()[selectData()$indicator == unique(selectData()$indicator)[5],],WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[5],1])+
          theme(
            axis.title.y = element_blank()
          )+
          labs(
            title = WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[5],1]
          )}
      else
      {return(NULL)}
     },ignoreNULL = FALSE)
    
    #6# 
    plot6 <- eventReactive(input$update,{
      if (n()==6){line_plot(selectData()[selectData()$indicator == unique(selectData()$indicator)[6],],WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[6],1])+
          theme(
            axis.title.y = element_blank()
          )+
          labs(
            title = WDI_Indicators[WDI_Indicators$Indicator.Code==indicator.list()[6],1]
          )}
      else
      {return(NULL)}
     },ignoreNULL = FALSE)

    output$plot1 = renderPlotly({plot1()}) 
    output$plot2 = renderPlotly({plot2()}) 
    output$plot3 = renderPlotly({plot3()}) 
    output$plot4 = renderPlotly({plot4()}) 
    output$plot5 = renderPlotly({plot5()}) 
    output$plot6 = renderPlotly({plot6()}) 

          
     #4#
      output$data <- renderTable({
        plotdata<-selectData()
        brushedPoints(plotdata, input$plot_brush)
      })
  }
)
```
